-- 1. Activer l'extension pour les UUIDs si ce n'est pas déjà fait
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Création de la table des sessions
CREATE TABLE IF NOT EXISTS sessions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code TEXT UNIQUE NOT NULL,
  
  -- Utilisateur 1 (Hôte)
  user1_id TEXT NOT NULL,
  user1_display_name TEXT,
  user1_playlist_id TEXT,
  user1_tracks JSONB,
  
  -- Utilisateur 2 (Invité)
  user2_id TEXT,
  user2_display_name TEXT,
  user2_playlist_id TEXT,
  user2_tracks JSONB,
  
  status TEXT DEFAULT 'waiting', -- waiting, active, finished
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Si la table existe déjà (déjà créée sans colonnes tracks), ajoute-les
ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS user1_tracks JSONB,
  ADD COLUMN IF NOT EXISTS user2_tracks JSONB;

-- 3. Création de la table des swipes
CREATE TABLE IF NOT EXISTS swipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID REFERENCES sessions(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  track_id TEXT NOT NULL,
  direction TEXT NOT NULL, -- 'left' or 'right'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Index pour la performance
CREATE INDEX IF NOT EXISTS idx_sessions_code ON sessions(code);
CREATE INDEX IF NOT EXISTS idx_swipes_session ON swipes(session_id);

-- 5. Activer le Realtime pour ces tables
-- Exécute ceci dans l'onglet SQL pour permettre l'écoute en temps réel
ALTER PUBLICATION supabase_realtime ADD TABLE sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE swipes;
